services: 
  tsu-backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5243:80"
    depends_on:
      - tsu-debugger
  tsu-frontend:
    ports:
      - "8080:80"
  tsu-nginx:
    ports:
      - "80:80"
  tsu-adminer:
    ports:
      - "8081:8080"
  tsu-psql:
    environment:
      POSTGRES_DB: tsu
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "6789:5432"
  tsu-debugger:
    container_name: tsu-debugger
    build: images/debugger
    image: tsu-debugger