services:
  tsu-nginx:
    container_name: tsu-nginx
    image: nginx:1.23.3
    volumes:
      - ../hb-docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - tsu-backend
      - tsu-frontend
      - tsu-psql
  tsu-frontend:
    container_name: tsu-frontend
    build:
      context: ../hb-front
    image: tsu-frontend
  tsu-backend:
    container_name: tsu-backend
    build:
      context: ../hb-back
    image: tsu-backend
    develop:
      watch:
        - action: rebuild
          path: ../hb-back
    volumes:
      - xlsx:/app/xlsx
    depends_on:
      - tsu-psql
  tsu-psql:
    image: postgres:latest
    container_name: tsu-psql
    restart: always
    volumes:
      - tsu_db:/var/lib/postgresql/data
  tsu-adminer:
    image: adminer:latest
    container_name: tsu-adminer
    restart: always

volumes:
  tsu_db:
  xlsx:
