services:
  tsu-backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    develop:
      watch:
        - action: rebuild
          path: ../hb-back

  tsu-psql:
    environment:
      POSTGRES_DB: tsu
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
