services:
  tsu-nginx:
    container_name: tsu-nginx
    build:
      context: ../hb-front
    image: tsu-nginx
    volumes:
      - ../hb-docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - tsu-backend
      - tsu-psql
  tsu-backend:
    container_name: tsu-backend
    build:
      context: ../hb-back
    image: tsu-backend
    develop:
      watch:
        - action: rebuild
          path: ../hb-back
    volumes:
      - storage:/app/Storage
    depends_on:
      - tsu-psql
  tsu-psql:
    image: postgres:latest
    container_name: tsu-psql
    restart: always
    volumes:
      - tsu_db:/var/lib/postgresql/data
  tsu-adminer:
    image: adminer:latest
    container_name: tsu-adminer
    restart: always

volumes:
  tsu_db:
  storage:
