#!/bin/bash

# Set the locale to Russian
export LC_ALL=ru_RU.UTF-8

# Get the absolute path of the script's directory
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P )
backend_folder="$parent_path/../../hb-back"
echo "$backend_folder"

# Check backend
BACKEND_FILES=$(git diff --cached --name-only --diff-filter=ACMRTUXB | grep '^hb-back' | sed 's/hb-back\///')
if [[ ${#BACKEND_FILES} > 0 ]]; then
	pushd "$backend_folder"
	
	dotnet-format --check -v m
	val=$?

	if [ $val -ne 0 ]; then
		echo -en "Backend code not formatted"
		exit 1
	fi

	popd
fi

exit 0